//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections; 
//namespace AssemblyCSharp
//{
public class LobbyPlayer : MonoBehaviour
{

	public LobbyPlayer ()
	{

	}

	 
	void OnGUI()
	{
		if (GUILayout.Button ("CREATE ROOM")) {
			Debug.Log("your pressed buttom");
		}
		if (GUILayout.Button ("JOIN ROOM2")) {

		}
		if (GUILayout.Button ("Play VS Comput")) {
			this.enabled = false;
			gameObject.AddComponent<PlayerGame>();
			//PlayerGame acomponent  = gameObject.GetComponent("PlayerGame") as PlayerGame;
			//Debug.Log (acomponent);

		}
		 
	}

}
//}

